### PR TITLE
Set TLS_CA_File for all platforms by default

### PR DESCRIPTION
**Pull request by chewi**
This is a cleaner rework of @sjourdan's pull request in #21 so kudos to him. It isn't clear whether this issue affects other platforms but it doesn't hurt to set it so let's do so just in case.

### CODE REVIEW

**Comment by chewi** [comment]
Fixed a Rubocop offence. The other two weren't being reported before and they weren't introduced by this commit anyway.

**Comment by drenalin23** [comment]
+1 as this improves multi-OS support

**Comment by chewi** [comment]
Rebased!

**Comment by mburns** [comment]
👍 thanks for this!

**Pull request merged**
