### PR TITLE
Adds support for revaliases file

### PR DESCRIPTION
**Pull request by cfreeman**
Lets you configure the revaliases file with chef.

### CODE REVIEW

**Comment by svanzoest** [comment]
@mburns a transfer of this repo is still pending, please accept as I am no longer maintaining this.

**Comment by mburns** [comment]
@svanzoest I don't see the notification anywhere to accept, sorry. Could you resend? Sorry for the trouble.

**Comment by svanzoest** [comment]
@mburns done! I think you can also go to the repos page and it may show you a prompt.

**Comment by mburns** [comment]
Success! Thanks @svanzoest.

@cfreeman I'll get this reviewed and merged shortly. Cheers!

**Comment by mburns** [comment]
This got lost in the shuffle. Mea culpa.

**Pull request merged**
